# -*- coding: utf-8 -*-
"""HTML QUICK STYLER.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1x7YbZ1DtnK51knJL7b1o7S663_otShfJ
"""

!pip install -U transformers

"""## Local Inference on GPU
Model page: https://huggingface.co/ibm-granite/granite-3.3-2b-instruct

⚠️ If the generated code snippets do not work, please open an issue on either the [model repo](https://huggingface.co/ibm-granite/granite-3.3-2b-instruct)
			and/or on [huggingface.js](https://github.com/huggingface/huggingface.js/blob/main/packages/tasks/src/model-libraries-snippets.ts) 🙏
"""

# Use a pipeline as a high-level helper
from transformers import pipeline

pipe = pipeline("text-generation", model="ibm-granite/granite-3.3-2b-instruct")
messages = [
    {"role": "user", "content": "Who are you?"},
]
pipe(messages)



!pip install -q gradio

import gradio as gr
import json
import re
from datetime import datetime
from typing import Tuple, Dict, List
import random

import gradio as gr

# ============================================================================
# MULTI-THEME PRO STYLER - FULL PINK INTERFACE EDITION
# ============================================================================

class ColorPaletteGenerator:
    @staticmethod
    def get_palette(theme: str) -> dict:
        palettes = {
            'Corporate Slate': {
                'primary': '#0F172A', 'bg': '#F8FAFC',
                'surface': '#FFFFFF', 'text': '#1E293B', 'border': '#E2E8F0'
            },
            'Cyber Dark': {
                'primary': '#00F2FF', 'bg': '#050505',
                'surface': '#0D0D0D', 'text': '#E0E0E0', 'border': '#1F1F1F'
            },
            'Nordic Forest': {
                'primary': '#2D3A3A', 'bg': '#F4F1EA',
                'surface': '#FFFFFF', 'text': '#2D3A3A', 'border': '#D1CDBE'
            },
            'Royal Gold': {
                'primary': '#1A1A1A', 'bg': '#FFFFFF',
                'surface': '#FAFAFA', 'text': '#1A1A1A', 'border': '#E5E5E5'
            }
        }
        return palettes.get(theme, palettes['Corporate Slate'])

class HTMLGenerator:
    @staticmethod
    def generate(title, description, theme_name):
        p = ColorPaletteGenerator.get_palette(theme_name)
        baby_pink = "#FFD1DC"
        baby_pink_hover = "#FFB7C5"

        border_radius = "0px" if theme_name == "Royal Gold" else "12px"
        button_radius = "4px" if theme_name == "Royal Gold" else "50px"

        css = f'''
        <style>
            @import url('https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@400;600;800&family=Playfair+Display:wght@700&display=swap');
            :root {{
                --primary: {p['primary']}; --accent: {baby_pink};
                --accent-hover: {baby_pink_hover}; --bg: {p['bg']};
                --surface: {p['surface']}; --text: {p['text']};
                --border: {p['border']}; --radius: {border_radius};
                --btn-radius: {button_radius};
            }}
            * {{ margin: 0; padding: 0; box-sizing: border-box; transition: all 0.3s ease; }}
            body {{ background: var(--bg); color: var(--text); font-family: 'Plus Jakarta Sans', sans-serif; }}
            nav {{ padding: 1.5rem 10%; display: flex; justify-content: space-between; background: var(--surface); border-bottom: 1px solid var(--border); position: sticky; top: 0; z-index: 100; }}
            .hero {{ padding: 100px 10%; text-align: center; max-width: 900px; margin: 0 auto; }}
            h1 {{ font-size: clamp(2.5rem, 6vw, 4rem); font-weight: 800; letter-spacing: -0.04em; line-height: 1.1; margin-bottom: 1.5rem; font-family: "{'Playfair Display' if theme_name == 'Royal Gold' else 'Plus Jakarta Sans'}"; }}
            .grid {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(280px, 1fr)); gap: 24px; padding: 0 10% 80px; max-width: 1200px; margin: 0 auto; }}
            .card {{ background: var(--surface); border: 1px solid var(--border); padding: 35px; border-radius: var(--radius); }}
            .btn {{ padding: 16px 35px; background: var(--accent); color: #333333; text-decoration: none; border-radius: var(--btn-radius); font-weight: 700; display: inline-block; font-size: 0.8rem; letter-spacing: 1px; text-transform: uppercase; border: 1px solid rgba(0,0,0,0.05); cursor: pointer; }}
            .btn:hover {{ background: var(--accent-hover); transform: scale(1.03); box-shadow: 0 8px 20px rgba(255, 209, 220, 0.4); }}
            footer {{ padding: 60px; text-align: center; border-top: 1px solid var(--border); opacity: 0.5; font-size: 0.8rem; }}
        </style>
        '''

        html = f'''
        <!DOCTYPE html>
        <html lang="en">
        <head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0">{css}</head>
        <body>
            <nav><div style="font-weight:800; letter-spacing:1px; color:var(--primary);">{title.upper()}</div></nav>
            <section class="hero">
                <h1>Crafting the Future <br>with Precision.</h1>
                <p style="margin-bottom:35px; opacity:0.7;">{description}</p>
                <a href="#" class="btn">Launch Project</a>
            </section>
            <div class="grid">
                <div class="card"><h3>Architecture</h3><p style="opacity:0.6;">Modern logic for high-scale applications.</p></div>
                <div class="card"><h3>Engineering</h3><p style="opacity:0.6;">Production-ready code with Python & FastAPI.</p></div>
                <div class="card"><h3>Aesthetics</h3><p style="opacity:0.6;">Minimalist design systems for 2026.</p></div>
            </div>
            <footer>&copy; 2026 {title} | Minimalist Studio</footer>
        </body>
        </html>
        '''
        return html

# --- Custom CSS for Gradio UI Elements ---
custom_ui_css = """
#generate_btn {
    background-color: #FFD1DC !important;
    color: #333333 !important;
    border: none !important;
    font-weight: bold !important;
    transition: all 0.3s ease !important;
}
#generate_btn:hover {
    background-color: #FFB7C5 !important;
    transform: translateY(-2px) !important;
    box-shadow: 0 5px 15px rgba(255, 209, 220, 0.4) !important;
}
"""

def update_preview(name, desc, theme):
    code = HTMLGenerator.generate(name, desc, theme)
    return code, code

with gr.Blocks(css=custom_ui_css, title="Pro Styler") as demo:
    gr.Markdown("# 🌸 Professional Build Generator")
    with gr.Row():
        with gr.Column(scale=1):
            name = gr.Textbox(label="Brand/Project Name", value="Aether Studio")
            desc = gr.Textbox(label="Vision Statement", value="The intersection of elite engineering and minimalist aesthetics.")
            theme = gr.Radio(
                ["Corporate Slate", "Cyber Dark", "Nordic Forest", "Royal Gold"],
                label="Environment Select",
                value="Corporate Slate"
            )
            # We add the elem_id here so the CSS above knows which button to style
            generate_btn = gr.Button("Generate Build", variant="primary", elem_id="generate_btn")

        with gr.Column(scale=2):
            code_out = gr.Code(label="Source Code", language="html")
            preview = gr.HTML()

    generate_btn.click(update_preview, [name, desc, theme], [code_out, preview])

if __name__ == "__main__":
    demo.launch()